name: setup-devcontainer
services:
  setup-devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .user_guid.env
    volumes:
      - ${TARGET_PATH:-./data/target}:/app/data/target
      - ${CONFIG_FILEPATH:-./config/config.json}:/app/config/config.json
    image: setup-devcontainer
