name: NAME_PLACEHOLDER
services:
  NAME_PLACEHOLDER:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    env_file:
      - .user_guid.env
    image: NAME_PLACEHOLDER
    stdin_open: true
    tty: true
